---
title: "p8105_hw2_sal2222"
author: "Stephen Lewandowski"
date: "November 9, 2018"
output: 
  github_document:
    toc: true
---

```{r setup, include = FALSE}

library(tidyverse)
library(readxl)
library(devtools)
library(p8105.datasets) #devtools::install_github("p8105/p8105.datasets")

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

# Problem 1 - Arm longitudinal study 

I will create a tidy dataframe from all participants, including the subject ID, arm, and observations over time. The raw data includes 20 files, one for each subject, each with eight weeks of observations arranged in wide format.

```{r import and tidy}


files <- list.files(path = "./data", pattern = "*.csv", full.names = TRUE) %>% 
  set_names()

import_file <- function(filename) 
{ 
  arm_file <- read.csv(file = filename) %>% 
     gather(key = week, value = value)
} 

output = map_dfr(.x = files, import_file, .id = "file_name")

output

 
```


